version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: local-mariadb
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: testdb
      MARIADB_USER: user
      MARIADB_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOST: mariadb
      PMA_USER: user
      PMA_PASSWORD: secret
    ports:
      - "8081:80"

volumes:
  mariadb_data: