spring:
    datasource:
        url: jdbc:mariadb://localhost:3306/testdb
        driver-class-name: org.mariadb.jdbc.Driver
        username: user
        password: secret
    jpa:
        hibernate:
            ddl-auto: create-drop
        database-platform: org.hibernate.dialect.MySQLDialect
        show-sql: true
        properties:
            hibernate.format_sql: true
logging:
    level:
        org:
            springframework:
                security=DEBUG:
server:
    error:
        include-message: always
        include-binding-errors: always
        include-stacktrace: never