spring:
    datasource:
        url: jdbc:mariadb://localhost:3306/testdb
        driver-class-name: org.mariadb.jdbc.Driver
        username: user
        password: secret
    jpa:
#        hibernate:
#            ddl-auto: update
        database-platform: org.hibernate.dialect.MySQL8Dialect
        show-sql: true
        properties:
            hibernate.format_sql: true